name: Sinetamer
favicon: null
layout_spectrum: 0.47773222299292684
typography_spectrum: 0.5598840012680739
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7380010904744267
  lightness: 0.47173627582378685
  saturation: 0.04517476377077401
  rhythmicContrast: 0.450140543282032
purpose: []
